name: CI/CD Pipeline with Selenium Tests

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      
      - name: Run Selenium tests
        run: |
         
          python -m pytest tests/selenium
         

       

            
            
        
                
       
     
